services:
  ai-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supervia-ai-service
    restart: unless-stopped
    ports:
      - "3004:3004"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - supervia-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  supervia-network:
    external: true
    name: infra_supervia-network 